src/dashboard/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import (
    DashboardView,
    # ProfileView,
    ProfileUpdateView,
	ProductCreateView,
	ProductUpdateView,
    ProductListView,
    ProductDeleteView,
    product_image_update,
    # ProductDetailView,
    SubscriptionView,
    ClientRequestCreateView,
    client_request_sent,
    ClientRequestDashboardCreate,
    ClientRequestUpdateView,
    ClientRequestListView,
    ClientRequestDetailView,
    ClientRequestDeleteView,
    MyMessageListView,
    MyMessageDetailView,
    MyMessageDeleteView,
    Error404View,
    # CategoryDetailView,
    # list_view,
    # detail_slug_view,
    # ProductRatingAjaxView,
    WishlistView,
    WishlistDeleteView,
    BoostedAjaxView,
    FeatureAjaxView,
    AvailableAjaxView,
    )

app_name = 'dashboard'

urlpatterns = [
    # path('category/<slug:category>/', CategoryDetailView.as_view(), name='category'),
    # path('<slug:slug>/', detail_slug_view, name='detail'),
    # path('<int:pk>/', ProductDetailView.as_view(), name='detail'),  
    # path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    path('property/<slug:slug>/image/', product_image_update, name='product_image_update'),
    path('property/<slug:slug>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('property/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('property/add/', ProductCreateView.as_view(), name='product_create'),
    path('properties/', ProductListView.as_view(), name='product_list'),
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    # path('<slug:slug>/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('client-request/<slug:slug>/update/', ClientRequestUpdateView.as_view(), name='client_request_update'),
    path('client-request/<slug:slug>/delete/', ClientRequestDeleteView.as_view(), name='client_request_delete'),
    path('client-request/dashboard-create/', ClientRequestDashboardCreate.as_view(), name='client_request_dashboard_create'),
    path('client-request/create/', ClientRequestCreateView.as_view(), name='client_request_create'),    
    path('client-request/sent/', client_request_sent, name='client_request_sent'),
    path('client-request/<slug:slug>/', ClientRequestDetailView.as_view(), name='client_request_detail'),
    path('client-request/', ClientRequestListView.as_view(), name='client_request_list'),
    path('message/<slug:slug>/delete/', MyMessageDeleteView.as_view(), name='my_message_delete'),
    path('message/<slug:slug>/', MyMessageDetailView.as_view(), name='my_message_detail'),
    path('message/', MyMessageListView.as_view(), name='my_message_list'),
    path('wishlist/<int:pk>/delete', WishlistDeleteView.as_view(), name='wishlist_delete'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('ajax/boosted/', BoostedAjaxView.as_view(), name='ajax_product_boosted'),
    path('ajax/feature-ad/', FeatureAjaxView.as_view(), name='ajax_product_featured'),
    path('ajax/available/', AvailableAjaxView.as_view(), name='ajax_product_available'),
    path('404/', Error404View.as_view(), name='404'),
    path('home/', DashboardView.as_view(), name='home'),
]

src/homelink/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from .sitemaps import StaticViewSitemap, ProductSitemap

from contact.views import contact, contact_sent
from newsletter.views import newsletter
from .views import HomeView, about, terms, privacy, careers, advert

sitemaps = {
    'pages': StaticViewSitemap,
    'prop': ProductSitemap,
}



urlpatterns = [ 
    path('about/', about, name='about'),
    path('advert/', advert, name='advert'),
    path('careers/', careers, name='careers'),
    path('contact/', contact, name='contact'),
    path('contact/sent/', contact_sent, name='contact_sent'),  
    path('newsletter/', newsletter, name='newsletter'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),

    url(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    
    path('hl/admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')), 
    path('properties/', include('products.urls', namespace='products')),

    path('', HomeView.as_view(), name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	category_post_list,
	)

app_name = 'posts'

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	url(r'^category/(?P<slug>[\w-]+)/$', category_post_list, name='category'),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/products/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import (
    # home,
    # product_add,
	# ProductCreateView,
    ProductListView,
	# ProductUpdateView,
    ProductDetailRedirect,
    ProductDetailView,
    product_detail,
    # CategoryDetailView,
    # list_view,
    # detail_slug_view,
    # ProductRatingAjaxView,
    WishlistAjaxView,
    )

app_name = 'products'

urlpatterns = [
    path('<int:pid>/', ProductDetailRedirect.as_view(), name='product_redirect'),
    path('<int:pid>/<slug:slug>/', product_detail, name='product_detail'),
    path('<int:pid>/<slug:slug>/', ProductDetailView.as_view(), name='detail'),

    # path('category/<slug:category>/', CategoryDetailView.as_view(), name='category'),
    # path('<slug:slug>/', detail_slug_view, name='detail'),
    # path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    # path('add/', product_add, name='add'),
    # path('create/', ProductCreateView.as_view(), name='product_create'),
    # path('create/', ProductCreateView.as_view(), name='create'),
    # path('<slug:slug>/edit/', ProductUpdateView.as_view(), name='update'),
    # path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    path('ajax/wishlist/', WishlistAjaxView.as_view(), name='ajax_wishlist'),
    path('', ProductListView.as_view(), name='product_list'),
    # path('', ProductListView.as_view(), name='list'),
    # path('', ProductListView, name='list'),
]

src/dashboard/views.py
import random
from django.utils import timezone
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View 
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
from django.forms import inlineformset_factory 
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from homelink.mixins import (
    LoginRequiredMixin,
    StaffRequiredMixin,
    MultiSlugMixin,
    FilterMixin,
    AjaxRequiredMixin
    )

from products.mixins import ProductOwnerMixin
from products.forms import ProductForm
from products.models import Product, ProductImage, Wishlist

from .mixins import ProfileMixin, OwnerMixin, MessageOwnerMixin
from .models import Profile, ClientRequest, MyMessage
from .forms import SignupForm, ProfileForm, ClientRequestForm 





class DashboardView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "dashboard/home.html"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(**kwargs)
        product = Product.objects.filter(realtor=self.request.user.profile)
        query = self.request.GET.get("search")
        if query:
            qs = product.filter(
                    Q(title__icontains=query)|
                    Q(category__icontains=query)|
                    Q(description__icontains=query)
                ).distinct()
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["today"] = timezone.now()
        return context



class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile 
    form_class = ProfileForm
    template_name = "dashboard/profile_update.html"
    success_url = reverse_lazy('dashboard:profile_update')
    submit_btn = "Update Profile"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def form_valid(self, form):
        valid_data = super().form_valid(form)
        messages.success(self.request, "Profile updated successfully!")
        return valid_data

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["today"] = timezone.now()
        return context




class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = "dashboard/product_create.html"
    form_class = ProductForm 

    def form_valid(self, form):
        user = self.request.user.profile
        form.instance.realtor = user
        valid_data = super().form_valid(form)
        messages.success(self.request, "Property has been added.")
        return valid_data

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["today"] = timezone.now()
        return context

    def get_success_url(self):
        pid = self.object.pid
        return reverse("dashboard:product_image_update", args=[pid])



class ProductUpdateView(ProductOwnerMixin, UpdateView):
    model = Product
    form_class = ProductForm 
    slug_field = 'pid'
    template_name = "dashboard/product_update.html"
    success_url = reverse_lazy('dashboard:product_list')
    submit_btn = "Update Product"

    def form_valid(self, form):
        valid_data = super().form_valid(form)
        messages.success(self.request, "Property updated!")
        obj = self.get_object()
        return valid_data

 

class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "dashboard/product_list.html"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(**kwargs)
        qs = Product.objects.filter(realtor=self.request.user.profile)
        query = self.request.GET.get("search")
        if query:
            qs = qs.filter(
                    Q(pid__iexacts=query)|
                    Q(title__icontains=query)|
                    Q(category__icontains=query)|
                    Q(property_type__icontains=query)|
                    Q(description__icontains=query)
                ).distinct()
        paginator = Paginator(qs, 10) # show 10 propertiess per page
        page = self.request.GET.get('page')
        qs = paginator.get_page(page)
        return qs


class ProductDeleteView(ProductOwnerMixin, DeleteView):
    model = Product
    slug_field = 'pid'
    success_url = reverse_lazy('dashboard:product_list')
    template_name = "dashboard/product_confirm_delete.html"



method_decorator(login_required)
def product_image_update(request, slug):
    obj = Product.objects.get(pid=slug)
    # obj = get_object_or_404(Product, pid=slug)
    ThumbnailInlineFormSet = inlineformset_factory(Product, ProductImage, fields=('media',), max_num=5, extra=5)
    if request.method == "POST":
        formset = ThumbnailInlineFormSet(request.POST, request.FILES, instance=obj)
        if formset.is_valid():
            formset.save()         
            messages.success(request, "Property Images updated!")
            return HttpResponseRedirect('/dashboard/properties/') #reverse('dashboard:product_list')
    else:
        formset = ThumbnailInlineFormSet(instance=obj)
    context = {
        'formset': formset
    }
    return render(request, 'dashboard/product_image_update.html', context)




class SubscriptionView(ProfileMixin, FormMixin, View):
    model = Profile

    def get(self, request, *args, **kwargs):
        account = self.get_account()
        context = {}
        context["profile"] = account 
        return render(request, "dashboard/subscription.html", context)




class ClientRequestCreateView(LoginRequiredMixin, CreateView):
    model = ClientRequest
    form_class = ClientRequestForm 
    template_name = "dashboard/client_request_create.html" 
    success_url = reverse_lazy('dashboard:client_request_sent')

    def form_valid(self, form):
        user = self.request.user.profile
        form.instance.user = user
        valid_data = super().form_valid(form)
        messages.success(self.request, "Property Request sent!")
        return valid_data

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["product_list"] = Product.objects.get_products()[:3]
        return context



def client_request_sent(request):
    contact_title = 'Request Sent Successfully'
    context = {
        "product_list": Product.objects.get_products()[:3],
    }
    return render(request, "dashboard/client_request_sent.html", context)




class ClientRequestDashboardCreate(LoginRequiredMixin, CreateView):
    model = ClientRequest
    form_class = ClientRequestForm 
    template_name = "dashboard/client_request_create_dashboard.html" 

    def form_valid(self, form):
        user = self.request.user.profile
        form.instance.user = user
        valid_data = super().form_valid(form)
        messages.success(self.request, "Property Request sent!")
        return valid_data

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["product_list"] = Product.objects.get_products()[:3]
        return context

    def get_success_url(self):
        ref = self.object.ref
        return reverse("dashboard:client_request_detail", kwargs={"slug": ref})



class ClientRequestUpdateView(OwnerMixin, UpdateView):
    model = ClientRequest
    form_class = ClientRequestForm
    slug_field = 'ref'
    template_name = "dashboard/client_request_create.html"
    success_url = reverse_lazy('dashboard:client_request_detail')
    submit_btn = "Update Request"

    def form_valid(self, form):
        valid_data = super().form_valid(form)
        messages.success(self.request, "Request updated!")
        obj = self.get_object()
        return valid_data

    def get_success_url(self):
        obj = self.get_object()
        ref = obj.ref
        return reverse("dashboard:client_request_detail", kwargs={"slug": ref})



class ClientRequestListView(LoginRequiredMixin, ListView):
    model = ClientRequest
    template_name = "dashboard/client_request_list.html"

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(**kwargs)
        qs = ClientRequest.objects.all()
        query = self.request.GET.get("search")
        if query:
            qs = qs.filter(
                    Q(ref__iexacts=query)|
                    Q(category__icontains=query)|
                    Q(state__icontains=query)|
                    Q(locality__icontains=query)|
                    Q(comment__icontains=query)
                ).distinct()
        paginator = Paginator(qs, 12) # show 12 propertiess per page
        page = self.request.GET.get('page')
        qs = paginator.get_page(page)
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["today"] = timezone.now()
        return context



import random
class ClientRequestDetailView(LoginRequiredMixin, DetailView):
    model = ClientRequest
    slug_field = "ref"
    template_name = "dashboard/client_request_detail.html"



class ClientRequestDeleteView(OwnerMixin, DeleteView):
    model = ClientRequest
    slug_field = 'ref'
    success_url = reverse_lazy('dashboard:client_request_list')
    template_name = "dashboard/client_request_confirm_delete.html"





class MyMessageListView(LoginRequiredMixin, ListView):
    model = MyMessage

src/templates/dashboard/client_request_confirm_delete.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load humanize %}
{% load crispy_forms_tags %}



    <!-- Page Content -->
    <div id="page-wrapper">
        {% block content %}
        <div class="container-fluid">
            <div class="row bg-title">
                {% include 'messages_display.html' %}
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Delete Request</h4> </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
                    <a href="/accounts/logout/" class="btn btn-danger btn-sm hidden-xs pull-right m-l-20 btn-rounded btn-outline waves-effect waves-light">Logout</a>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'dashboard:home' %}">Dashboard</a></li>
                        <li><a href="{% url 'dashboard:client_request_list' %}">Client Request</a></li>
                        <li class="active">Delete</li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->


            <!-- .row -->
            <div class="row">
                <div class="col-md-8 col-xs-12">
                    <div class="white-box">                        
                        <p class="lead text-center">Are you sure you want to delete this request?</p>
                        <hr>
                        <form method="POST">{% csrf_token %}
                            <ul class="price-list client-request">
                                <li><p><b>Ref:</b> {{ object.ref }}<br>
                                    <b>Category:</b> {{ object.category }}<br>
                                    <b>Number of bedroom(s):</b> {{ object.bedroom }}<br>
                                    <b>State:</b> {{ object.state }}<br>
                                    <b>Locality:</b> {{ object.locality }}<br>
                                    <b>Maximum budget:</b> &#8358; {{ object.budget|floatformat|intcomma }}<br> 
                                    <b>Request date:</b> {{ object.timestamp|date }}<br>
                                    <b>Comment:</b><br> {{ object.get_markdown }}</p>
                                </li>
                                <li>
                                    <button class="btn btn-danger"><i class="fa fa-trash"></i> Confirm Delete</button>
                                    <a href="{% url 'dashboard:client_request_list' %}" class="btn btn-info"><i class="fa fa-times"></i> Cancel</a>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                  <ul class="price-list white-box">
                    <a href="{% url 'dashboard:product_list' %}">
                    <li class="lead">My Listing</li>
                    <li><p><i class="fa fa-building fa-3x"></i></p> <p> Boost, Feature, and Edit your listings</p></li>
                    </a>
                  </ul>
                  <ul class="price-list white-box">
                    <a href="{% url 'dashboard:subscription' %}">
                    <li class="lead">My Subscription</li>
                    <li><p><i class="fa fa-credit-card fa-3x"></i></p> <p> Subscribe, Upgrade, Renew and Top-up your products</p></li>
                    </a>
                  </ul>
                  <ul class="price-list white-box">
                    <li class="lead">Do you need help?</li>
                    <li><p><i class="fa fa-support fa-2x"></i></p> <p> Contact us using the details below. <br> <i class="fa fa-phone"></i> 0809 446 6080 <br><i class="fa fa-envelope-o"></i> support@homelink.ng</p></li>
                  </ul>
                </div>
                
            </div>
            <!-- /.row -->
        </div>
        {% endblock content %}
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
   

{% block scripts %}
    <!-- jQuery -->
    <script src="{% static 'dashboard/plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'dashboard/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'dashboard/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dashboard/js/waves.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dashboard/js/custom.min.js' %}"></script>
{% endblock scripts %}

src/templates/dashboard/profile_update_prompt.html
<ul class="price-list">
    <li class="header bg-danger">Profile not up to date</li>
    <li class="text-bolder">Name: {{ request.user.get_full_name }}</li>
    <li> 
      <span style="font-weight: bolder;">Kindly update your profile to get started</span><br>
      <a href="{% url 'dashboard:profile_update' %}" class="btn btn-danger">Update Profile</a>
    </li> 
    <li>
      <span class="text-muted color-bottom-txt">For assistance talk to our Support Team.<br> <i class="fa fa-phone"></i> <a>0809 446 6080</a> &nbsp;&nbsp; <i class="fa fa-envelope-o"></i> <a>support@homelink.ng</a></span>
    </li>
</ul>

src/templates/dashboard/profile_update_prompt_2.html
<!-- row -->
<div class="row">
    <div class="col-md-12">
      <div class="white-box text-center">
        <h3 class="page-title">Welcome back, {{ request.user.get_full_name }}</h3>
        <h3 class="page-title text-danger">Profile not up to date</h3>
        <!-- <p>Member Since: <i>{{ request.user.date_joined|date }}</i></p> -->
        <p> <span style="font-weight: bolder;">Kindly update your profile to get started</span></p> 
        <p><a href="{% url 'dashboard:profile_update' %}" class="btn btn-danger">Update Profile</a></p>
        <hr />
        <p>
            <span class="text-muted color-bottom-txt">For assistance talk to our Support Team.<br> <i class="fa fa-phone"></i> <a>0809 446 6080</a> &nbsp;&nbsp; <i class="fa fa-envelope-o"></i> <a>support@homelink.ng</a> 
            </span>
        </p>
      </div>
  </div>
</div>
<!-- /row -->

src/templates/dashboard/wishlist.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load humanize %}
{% load crispy_forms_tags %}



    <!-- Page Content -->
    <div id="page-wrapper">
        {% block content %}
        <div class="container-fluid">
            <div class="row bg-title">
                {% include 'messages_display.html' %}
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Saved Properties</h4> </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <a href="/accounts/logout/" class="btn btn-danger btn-sm hidden-xs pull-right m-l-20 btn-rounded btn-outline waves-effect waves-light">Logout</a>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'dashboard:home' %}">Dashboard</a></li>
                        <li class="active">Properties</li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->

            <!-- row -->      
            <div class="row">      
            {% for i in object_list %}
                <div class="col-md-4">
                    <ul class="white-box price-list">
                        <a href="{{ i.product.get_absolute_url }}">
                            {% if i.product.get_image_url %}
                            <img src="{{ i.product.get_image_url }}" class="img-responsive img-thumbnai" alt="">
                            {% else %}
                            <img src="{% static 'images/no_image.png' %}" class="img-responsive" alt="">
                            {% endif %}
                        </a>
                        <li>
                            <span class="lead"><a href="{{ i.product.get_absolute_url }}">{{ i.product.title }}</a></span><br>
                            <span>{{ i.product.address }}, {{ i.product.city }}, {{ i.product.state }}</span><br>
                            <span>PID: {{ i.product.pid }}</span> 
                        </li>
                        <li>
                            <span>{{ i.product.category }} ({{ i.product.property_type }})</span><br>
                            <span>Saved on: {{ i.timestamp }}</span><br>
                            <span class="lead">&#8358; {{ i.product.price|floatformat|intcomma }}</span><br>
                        </li>
                        <li>
                            <a href="{{ i.product.get_absolute_url }}" class="btn-sm btn-primary"><i class="fa fa-eye"></i> View Details</a>
                            <a href="{% url 'dashboard:wishlist_delete' pk=i.id %}" class="btn-sm btn-danger"><i class="fa fa-trash"></i> Remove</a>
                        </li>
                    </ul>
                </div>
            {% cycle '' '' '<div class="clearfix"></div>' %}
            {% empty %}
                <br><br><br>
                <li class="lead text-center">No property yet.</li>
                <br><br><br>
            {% endfor %}
            </div>            
            <!-- /row -->


            {% if object_list %}
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">
                        <div class="pagination">
                          <ul class="pagination">
                            {% if object_list.has_previous %}
                              <!-- <li><a href="?page=1"><i class="fa fa-arrow-left"></i> First</a></li> -->
                              <li><a href="?page={{ object_list.previous_page_number }}"> << Previous </a></li>
                            {% else %}
                              <!-- <li class="disabled"><a href="?page=1"><i class="fa fa-arrow-left"></i> First</a></li> -->
                              <li class="disabled"><a href="#"> << Previous </a></li>            
                            {% endif %}

                              <li><a> Page {{ object_list.number }} of {{ object_list.paginator.num_pages }} </a></li>

                            {% if object_list.has_next %}
                              <li><a href="?page={{ object_list.next_page_number }}"> Next >> </a></li>
                              <!-- <li><a href="?page={{ object_list.paginator.num_pages }}">Last <i class="fa fa-arrow-right"></i></a></li> -->
                            {% else %}            
                              <li class="disabled"><a href="#"> Next >> </a></li>
                              <!-- <li class="disabled"><a href="?page={{ object_list.paginator.num_pages }}">Last <i class="fa fa-arrow-right"></i></a></li> -->
                            {% endif %}
                          </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                  <div class="white-box text-center">
                    <h4 class="page-title">Do you need help? Contact Us.</h4>
                    <p><i class="fa fa-phone"></i> 0809 446 6080</p>
                    <p><i class="fa fa-envelope-o"></i> support@homelink.ng</p>
                  </div>
              </div>
            </div>
            <!-- /row -->
        </div>
        {% endblock content %}
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
   

{% block scripts %}
    <!-- jQuery -->
    <script src="{% static 'dashboard/plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{% static 'dashboard/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js' %}"></script>
    <!--slimscroll JavaScript -->
    <script src="{% static 'dashboard/js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'dashboard/js/waves.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dashboard/js/custom.min.js' %}"></script>
{% endblock scripts %}



{% block extra_scripts %}
    <!-- custom jquery -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.12.1/jquery-ui.product.min.js"></script>
    <!-- using jQuery -->
    <script type="text/javascript" src="{% static '/js/django.csrf.js' %}"></script>
   

{% endblock extra_scripts %}


 <!-- Adding item to wishlist -->
    <!-- <script>        
        $(document).ready(function(){
            $(".wishlist-btn").click(function(event){
                event.preventDefault()
                var obj_id = $(this).val()
                var request = $.ajax({
                    method: "POST",
                    url: "{% url 'products:ajax_wishlist' %}",
                    data: {
                        product_id: obj_id,         
                    }
                })
                request.done(function(data){
                    // console.log("working...")
                    if (data.success){
                        alert("Item added to wishlist successfully!.")
                    }
                })
                request.fail(function(jqXHR, textStatus){
                    if (jqXHR.status == 404) {
                        alert("Page not found!")
                    } else if (jqXHR.status == 401){
                        alert("You must be logged in to do this.")
                    } else {
                        alert("There was an error with your request. Please try again.")
                    }
                })
            })

        })
    </script> -->