src/dashboard/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import (
    DashboardView,
    # ProfileView,
    ProfileUpdateView,
	ProductCreateView,
	ProductUpdateView,
    ProductListView,
    ProductDeleteView,
    product_image_update,
    # ProductDetailView,
    SubscriptionView,
    ClientRequestCreateView,
    client_request_sent,
    ClientRequestDashboardCreate,
    ClientRequestUpdateView,
    ClientRequestListView,
    ClientRequestDetailView,
    ClientRequestDeleteView,
    MyMessageListView,
    MyMessageDetailView,
    MyMessageDeleteView,
    Error404View,
    # CategoryDetailView,
    # list_view,
    # detail_slug_view,
    # ProductRatingAjaxView,
    WishlistView,
    WishlistDeleteView,
    BoostedAjaxView,
    FeatureAjaxView,
    AvailableAjaxView,
    )

app_name = 'dashboard'

urlpatterns = [
    # path('category/<slug:category>/', CategoryDetailView.as_view(), name='category'),
    # path('<slug:slug>/', detail_slug_view, name='detail'),
    # path('<int:pk>/', ProductDetailView.as_view(), name='detail'),  
    # path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    path('property/<slug:slug>/image/', product_image_update, name='product_image_update'),
    path('property/<slug:slug>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('property/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('property/add/', ProductCreateView.as_view(), name='product_create'),
    path('properties/', ProductListView.as_view(), name='product_list'),
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    # path('<slug:slug>/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('client-request/<slug:slug>/update/', ClientRequestUpdateView.as_view(), name='client_request_update'),
    path('client-request/<slug:slug>/delete/', ClientRequestDeleteView.as_view(), name='client_request_delete'),
    path('client-request/dashboard-create/', ClientRequestDashboardCreate.as_view(), name='client_request_dashboard_create'),
    path('client-request/create/', ClientRequestCreateView.as_view(), name='client_request_create'),    
    path('client-request/sent/', client_request_sent, name='client_request_sent'),
    path('client-request/<slug:slug>/', ClientRequestDetailView.as_view(), name='client_request_detail'),
    path('client-request/', ClientRequestListView.as_view(), name='client_request_list'),
    path('message/<slug:slug>/delete/', MyMessageDeleteView.as_view(), name='my_message_delete'),
    path('message/<slug:slug>/', MyMessageDetailView.as_view(), name='my_message_detail'),
    path('message/', MyMessageListView.as_view(), name='my_message_list'),
    path('wishlist/<int:pk>/delete', WishlistDeleteView.as_view(), name='wishlist_delete'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('ajax/boosted/', BoostedAjaxView.as_view(), name='ajax_product_boosted'),
    path('ajax/feature-ad/', FeatureAjaxView.as_view(), name='ajax_product_featured'),
    path('ajax/available/', AvailableAjaxView.as_view(), name='ajax_product_available'),
    path('404/', Error404View.as_view(), name='404'),
    path('home/', DashboardView.as_view(), name='home'),
]

src/homelink/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from .sitemaps import StaticViewSitemap, ProductSitemap

from contact.views import contact, contact_sent
from newsletter.views import newsletter
from .views import HomeView, about, terms, privacy, careers, advert

sitemaps = {
    'pages': StaticViewSitemap,
    'prop': ProductSitemap,
}



urlpatterns = [ 
    path('about/', about, name='about'),
    path('advert/', advert, name='advert'),
    path('careers/', careers, name='careers'),
    path('contact/', contact, name='contact'),
    path('contact/sent/', contact_sent, name='contact_sent'),  
    path('newsletter/', newsletter, name='newsletter'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),

    url(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    
    path('hl/admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')), 
    path('properties/', include('products.urls', namespace='products')),

    path('', HomeView.as_view(), name='home'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	category_post_list,
	)

app_name = 'posts'

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	url(r'^category/(?P<slug>[\w-]+)/$', category_post_list, name='category'),
    # url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/products/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from .views import (
    # home,
    # product_add,
	# ProductCreateView,
    ProductListView,
	# ProductUpdateView,
    ProductDetailRedirect,
    ProductDetailView,
    product_detail,
    # CategoryDetailView,
    # list_view,
    # detail_slug_view,
    # ProductRatingAjaxView,
    WishlistAjaxView,
    )

app_name = 'products'

urlpatterns = [
    path('<int:pid>/', ProductDetailRedirect.as_view(), name='product_redirect'),
    path('<int:pid>/<slug:slug>/', product_detail, name='product_detail'),
    path('<int:pid>/<slug:slug>/', ProductDetailView.as_view(), name='detail'),

    # path('category/<slug:category>/', CategoryDetailView.as_view(), name='category'),
    # path('<slug:slug>/', detail_slug_view, name='detail'),
    # path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    # path('add/', product_add, name='add'),
    # path('create/', ProductCreateView.as_view(), name='product_create'),
    # path('create/', ProductCreateView.as_view(), name='create'),
    # path('<slug:slug>/edit/', ProductUpdateView.as_view(), name='update'),
    # path('ajax/rating/', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    path('ajax/wishlist/', WishlistAjaxView.as_view(), name='ajax_wishlist'),
    path('', ProductListView.as_view(), name='product_list'),
    # path('', ProductListView.as_view(), name='list'),
    # path('', ProductListView, name='list'),
]

src/newsletter/models.py
from django.db import models



class Newsletter(models.Model):
	email = models.EmailField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.email

src/newsletter/forms.py
from django import forms

from .models import Newsletter

class NewsletterForm(forms.ModelForm):
	class Meta:
		model = Newsletter
		fields = ['email']

	def clean_email(self):
		email = self.cleaned_data.get('email')
		return email

src/newsletter/views.py
from django.shortcuts import render

from products.models import Product
from .models import Newsletter
from .forms import NewsletterForm



def newsletter(request):
    form = NewsletterForm(request.POST or None)
    product_list = Product.objects.get_products()[:3]
    context = {
        'title': None,
		'form': form,
        'product_list': product_list,
    }
    if form.is_valid():
        form_email = form.cleaned_data.get("email")
        query = Newsletter.objects.filter(email=form_email)
        if query:
            title = "Already Subscribed"
        else:
            form.save()
            title = "Subscription Confirmed"
        context = {
            'title': title,
            'product_list': product_list,
        }
    return render(request, 'newsletter.html', context)

src/templates/base-account.html
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block head_title %}{% trans "Login" %}{% endblock %}</title>
    
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}">
  <!-- BOOTSTRAP STYLES-->
    <link href="{% static 'auth/css/bootstrap.css' %}" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="{% static 'auth/css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'auth/css/font-awesome.min.css' %}" rel="stylesheet" /> -->
        <!-- CUSTOM STYLES-->
    <link href="{% static 'auth/css/custom.css' %}" rel="stylesheet" />
     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>
<body>
     <div class="container">
        <div class="row text-center ">
            <div class="col-md-12">
                <br /><br /><br><br>
                <a class="logo" href="/"><img src="{% static 'images/hl-logo-g.png' %}" alt="Homelink.ng"></a>
                 <br /><br><br>
            </div>
        </div>
        {% block content %}
         <div class="row ">               
          <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
              <div class="panel panel-default">
                  <div class="panel-heading">
                  <strong><center>Login into Your Account</center></strong>  
                  </div>
                  <div class="panel-body">
                      <form role="form" method="POST" action="{% url 'account_login' %}">
                        {% csrf_token %}
                             <br />
                            {{ form|crispy }}
                           <button class="btn btn-success btn-block" type="submit">Login Now</button>
                          <hr />
                          <center>Not register ? <a href="{{ signup_url }}" > Sign Up </a> </center>
                      </form>
                  </div>                           
              </div>
          </div>
        </div>
        {% endblock content %}
    </div>



     <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="{% static 'auth/js/jquery-1.10.2.js' %}"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="{% static 'auth/js/bootstrap.min.js' %}"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="{% static 'auth/js/jquery.metisMenu.js' %}"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="{% static 'auth/js/custom.js' %}"></script>
   
</body>
</html>

src/templates/messages_display-1.html
{% block messages %}
    {% if messages %}
    <ul class="messagelist">{% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
    {% endfor %}</ul>
    {% endif %}
{% endblock messages %}

src/templates/navbar.html
{% load i18n %}
{% load staticfiles %}
{% load humanize %}


<!-- Header -->
	<header class="header">
		<div class="container">
			{% if messages %}
				{% include 'messages_display.html' %}
			{% endif %}
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="logo">
							<a href="/"><img src="{% static 'images/hl-logo-w.png' %}" alt=""></a>
						</div>
						<nav class="main_nav">
							<ul>
								<li {% if request.path == "/" %} class="active" {% endif %}><a href="/">Home</a></li>
								<!-- <li><a href="{% url 'products:product_list' %}?category=Sale">For Sale</a></li> -->
								<!-- <li><a href="{% url 'products:product_list' %}?category=Rent">For Rent</a></li> -->
								<!-- <li><a href="{% url 'products:product_list' %}?category=ShortLet">For ShortLet</a></li> -->
								<li {% if request.path == "/posts/" %} class="active" {% endif %}><a href="{% url 'posts:list' %}">News</a></li>
								<li {% if request.path == "/dashboard/client-request/create/" %} class="active" {% endif %}><a href="{% url 'dashboard:client_request_create' %}">Request Property</a></li>
								<li><a href="{% url 'dashboard:product_create' %}"> Post Property</a></li>
								{% if not user.is_authenticated %}
								<li><a href="/accounts/login/">Login</a> <span style="color: #FFF;">/</span> <a href="/accounts/signup/">Register</a></li>
								{% else %}
								<li><a href="{% url 'dashboard:home' %}">My Account</a> <span style="color: #FFF;">/</span> <a href="/accounts/logout/">Logout</a></li>
								{% endif %}
							</ul>
						</nav>
						<!-- <div class="phone_num ml-auto">
							<div class="phone_num_inner">
								<span> 
									{% if not user.is_authenticated %}
									<a href="/accounts/login/">Login</a> or <a href="/accounts/signup/">Register</a>
									{% else %}
									<a href="{% url 'dashboard:home' %}">My Dashboard</a> / <a href="/accounts/logout/">Logout</a>
									{% endif %}
								</span>
							</div>
						</div> -->
						<div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- Menu -->
	<div class="menu trans_500">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<div class="menu_close_container"><div class="menu_close"></div></div>
			<div class="logo menu_logo">
				<a href="#">
					<div class="logo_container d-flex flex-row align-items-start justify-content-start">
						<div class="logo_image"><div><img src="{% static 'images/logo.png' %}" alt=""></div></div>
					</div>
				</a>
			</div>
			<ul>
				<li class="menu_item"><a href="/">Home</a></li>
				<!-- <li class="menu_item"><a href="{% url 'products:product_list' %}?property_for=Sale">For Sale</a></li>
				<li class="menu_item"><a href="{% url 'products:product_list' %}?property_for=Rent">For Rent</a></li>
				<li class="menu_item"><a href="{% url 'products:product_list' %}?property_for=ShortLet">For ShortLet</a></li> -->
				<li class="menu_item"><a href="{% url 'posts:list' %}">News</a></li>
				<li class="menu_item"><a href="{% url 'dashboard:client_request_create' %}"> Request Property</a></li>
				<li class="menu_item"><a href="{% url 'dashboard:product_create' %}"> Post Property</a></li>
				<!-- <li class="menu_item"><a href="/about/">About us</a></li>
				<li class="menu_item"><a href="/properties/">Properties</a></li>
				<li class="menu_item"><a href="/contact/">Contact</a></li> -->
				{% if not user.is_authenticated %}
				<li class="menu_item"><a href="/accounts/login/">Login</a></li>
				<li class="menu_item"><a href="/accounts/signup/">Register</a></li>
				{% else %}
				<li class="menu_item"><a href="{% url 'dashboard:home' %}">My Account</a></li>
				<li class="menu_item"><a href="/accounts/logout/">Logout</a></li>
				{% endif %}
			</ul>
		</div>
		<!-- <a href="#"> -->
			<!-- <div class="menu_phone btn btn-success">
				<span>
					{% if not user.is_authenticated %}
					<a href="/accounts/login/">Login</a> <span style="color: #000;">or</span> <a href="/accounts/signup/">Register</a>
					{% else %}
					<a href="{% url 'dashboard:home' %}">My Dashboard</a> / <a href="/accounts/logout/">Logout</a>
					{% endif %}			
				</span>
			</div> -->
		<!-- </a> -->
	</div>

src/templates/search_sidebar.html
{% load i18n %}
{% load staticfiles %}
{% load humanize %}

<div class="sidebar_search">
	<div class="sidebar_search_title">Search for properties</div>
	<div class="sidebar_search_form_container">
		<form action="{% url 'products:product_list' %}" method="GET" class="sidebar_search_form" id="sidebar_search_form">
			<input class="sidebar_search_input" type="text" placeholder="Search Keywords . . ." name="q" value="{{ request.GET.q }}"><br/><br/>
			<select class="sidebar_search_select" name="state">
				<option disabled selected>- Select State -</option>
				<option {% if request.GET.state == 'Abia' %} selected {% endif %} value="Abia">Abia</option>
				<option {% if request.GET.state == 'Abuja' %} selected {% endif %} value="Abuja">Abuja</option>
				<option {% if request.GET.state == 'Adamawa' %} selected {% endif %} value="Adamawa">Adamawa</option>
				<option {% if request.GET.state == 'Akwa Ibom' %} selected {% endif %} value="Akwa Ibom">Akwa Ibom</option>
				<option {% if request.GET.state == 'Anambra' %} selected {% endif %} value="Anambra">Anambra</option>
				<option {% if request.GET.state == 'Bauchi' %} selected {% endif %} value="Bauchi">Bauchi</option>
				<option {% if request.GET.state == 'Bayelsa' %} selected {% endif %} value="Bayelsa">Bayelsa</option>
				<option {% if request.GET.state == 'Benue' %} selected {% endif %} value="Benue">Benue</option>
				<option {% if request.GET.state == 'Borno' %} selected {% endif %} value="Borno">Borno</option>
				<option {% if request.GET.state == 'Cross River' %} selected {% endif %} value="Cross River">Cross River</option>
				<option {% if request.GET.state == 'Delta' %} selected {% endif %} value="Delta">Delta</option>
				<option {% if request.GET.state == 'Ebonyi' %} selected {% endif %} value="Ebonyi">Ebonyi</option>
				<option {% if request.GET.state == 'Edo' %} selected {% endif %} value="Edo">Edo</option>
				<option {% if request.GET.state == 'Ekiti' %} selected {% endif %} value="Ekiti">Ekiti</option>
				<option {% if request.GET.state == 'Enugu' %} selected {% endif %} value="Enugu">Enugu</option>
				<option {% if request.GET.state == 'Gombe' %} selected {% endif %} value="Gombe">Gombe</option>
				<option {% if request.GET.state == 'Imo' %} selected {% endif %} value="Imo">Imo</option>
				<option {% if request.GET.state == 'Jigawa' %} selected {% endif %} value="Jigawa">Jigawa</option>
				<option {% if request.GET.state == 'Kaduna' %} selected {% endif %} value="Kaduna">Kaduna</option>
				<option {% if request.GET.state == 'Kano' %} selected {% endif %} value="Kano">Kano</option>
				<option {% if request.GET.state == 'Kastina' %} selected {% endif %} value="Kastina">Kastina</option>
				<option {% if request.GET.state == 'Kebbi' %} selected {% endif %} value="Kebbi">Kebbi</option>
				<option {% if request.GET.state == 'Kogi' %} selected {% endif %} value="Kogi">Kogi</option>
				<option {% if request.GET.state == 'Kwara' %} selected {% endif %} value="Kwara">Kwara</option>
				<option {% if request.GET.state == 'Lagos' %} selected {% endif %} value="Lagos">Lagos</option>
				<option {% if request.GET.state == 'Nasarawa' %} selected {% endif %} value="Nasarawa">Nasarawa</option>
				<option {% if request.GET.state == 'Niger' %} selected {% endif %} value="Niger">Niger</option>
				<option {% if request.GET.state == 'Ogun' %} selected {% endif %} value="Ogun">Ogun</option>
				<option {% if request.GET.state == 'Ondo' %} selected {% endif %} value="Ondo">Ondo</option>
				<option {% if request.GET.state == 'Osun' %} selected {% endif %} value="Osun">Osun</option>
				<option {% if request.GET.state == 'Oyo' %} selected {% endif %} value="Oyo">Oyo</option>
				<option {% if request.GET.state == 'Plateau' %} selected {% endif %} value="Plateau">Plateau</option>
				<option {% if request.GET.state == 'Rivers' %} selected {% endif %} value="Rivers">Rivers</option>
				<option {% if request.GET.state == 'Sokoto' %} selected {% endif %} value="Sokoto">Sokoto</option>
				<option {% if request.GET.state == 'Taraba' %} selected {% endif %} value="Taraba">Taraba</option>
				<option {% if request.GET.state == 'Yobe' %} selected {% endif %} value="Yobe">Yobe</option>
				<option {% if request.GET.state == 'Zamfara' %} selected {% endif %} value="Zamfara">Zamfara</option>
			</select>
			<select class="sidebar_search_select" name="category">
					<option disabled selected>- Category -</option>
	              	<option {% if request.GET.category == 'For Sale' %} selected {% endif %} value="For Sale">For Sale</option>
	              	<option {% if request.GET.category == 'For Rent' %} selected {% endif %} value="For Rent">For Rent</option  >
	              	<option {% if request.GET.category == 'For ShortLet' %} selected {% endif %} value="For ShortLet">For ShortLet</option>
			</select>
			<select class="sidebar_search_select" name="property_type">
				<option>- Property Type -</option>
					<!-- <option {% if request.GET.property_type == 'Apartment' %} selected {% endif %} value="Apartment">Apartment/Flat</option> -->
					<!-- <option {% if request.GET.property_type == 'Bungalow' %} selected {% endif %} value="Bungalow">Bungalow</option> -->
					<!-- <option {% if request.GET.property_type == 'Duplex' %} selected {% endif %} value="Duplex">Duplex</option> -->
					<!-- <option {% if request.GET.property_type == 'Self Contained' %} selected {% endif %} value="Self Contained">Self Contained</option> -->
					<option {% if request.GET.property_type == 'Residential' %} selected {% endif %} value="Land">Residential</option>
					<option {% if request.GET.property_type == 'Commercial' %} selected {% endif %} value="Commercial">Commercial</option>
					<option {% if request.GET.property_type == 'Land' %} selected {% endif %} value="Land">Land</option>
			</select>
			<div class="row sidebar_search_row">
				<div class="col-lg-6">
					<select class="sidebar_search_select" name="bedrooms">
						<option disabled selected>- Bedrooms -</option>
						<option {% if request.GET.bedrooms == '1' %} selected {% endif %} value="1"> 1 </option>
						<option {% if request.GET.bedrooms == '2' %} selected {% endif %} value="2"> 2 </option>
						<option {% if request.GET.bedrooms == '3' %} selected {% endif %} value="3"> 3 </option>
						<option {% if request.GET.bedrooms == '4' %} selected {% endif %} value="4"> 4 </option>
						<option {% if request.GET.bedrooms == '5' %} selected {% endif %} value="5"> 5 </option>
						<option {% if request.GET.bedrooms == '6' %} selected {% endif %} value="6"> 6+ </option>
					</select>
				</div>
				<div class="col-lg-6">
					<select class="sidebar_search_select" name="bathrooms">
						<option disabled selected>- Bathrooms -</option>
						<option {% if request.GET.bedrooms == '1' %} selected {% endif %} value="1"> 1 </option>
						<option {% if request.GET.bedrooms == '2' %} selected {% endif %} value="2"> 2 </option>
						<option {% if request.GET.bedrooms == '3' %} selected {% endif %} value="3"> 3 </option>
						<option {% if request.GET.bedrooms == '4' %} selected {% endif %} value="4"> 4 </option>
						<option {% if request.GET.bedrooms == '5' %} selected {% endif %} value="5"> 5 </option>
						<option {% if request.GET.bedrooms == '6' %} selected {% endif %} value="6"> 6+ </option>
					</select>
				</div>
			</div>
			<div class="row sidebar_search_row">
				<div class="col-lg-6">
					<select class="sidebar_search_select" name="min_price">
						<option disabled selected>- Min Price -</option>
						<option {% if request.GET.max_price == '100000' %} selected {% endif %} value="100000">&#8358; 100,000</option>
						<option {% if request.GET.max_price == '200000' %} selected {% endif %} value="200000">&#8358; 200,000</option>
						<option {% if request.GET.max_price == '500000' %} selected {% endif %} value="500000">&#8358; 500,000</option>
						<option {% if request.GET.max_price == '1000000' %} selected {% endif %} value="1000000">&#8358; 1 million</option>
						<option {% if request.GET.max_price == '2000000' %} selected {% endif %} value="2000000">&#8358; 2 million</option>
						<option {% if request.GET.max_price == '5000000' %} selected {% endif %} value="5000000">&#8358; 5 million</option>
						<option {% if request.GET.max_price == '10000000' %} selected {% endif %} value="10000000">&#8358; 10 million</option>
						<option {% if request.GET.max_price == '50000000' %} selected {% endif %} value="50000000">&#8358; 50 million</option>
						<option {% if request.GET.max_price == '100000000' %} selected {% endif %} value="100000000">&#8358; 100 million</option>
						<option {% if request.GET.max_price == '500000000' %} selected {% endif %} value="500000000">&#8358; 500 million</option>
						<option {% if request.GET.max_price == '1000000000' %} selected {% endif %} value="1000000000">&#8358; 1 billion</option>
						<option {% if request.GET.max_price == '50000000000' %} selected {% endif %} value="1000000000">&#8358; 50 billion</option>
						<option {% if request.GET.max_price == '100000000000' %} selected {% endif %} value="1000000000">&#8358; 100 billion</option>
					</select>
				</div>
				<div class="col-lg-6">
					<select class="sidebar_search_select" name="max_price">
						<option disabled selected>- Max Price -</option>
						<option {% if request.GET.max_price == '100000' %} selected {% endif %} value="100000">&#8358; 100,000</option>
						<option {% if request.GET.max_price == '200000' %} selected {% endif %} value="200000">&#8358; 200,000</option>
						<option {% if request.GET.max_price == '500000' %} selected {% endif %} value="500000">&#8358; 500,000</option>
						<option {% if request.GET.max_price == '1000000' %} selected {% endif %} value="1000000">&#8358; 1 million</option>
						<option {% if request.GET.max_price == '2000000' %} selected {% endif %} value="2000000">&#8358; 2 million</option>
						<option {% if request.GET.max_price == '5000000' %} selected {% endif %} value="5000000">&#8358; 5 million</option>
						<option {% if request.GET.max_price == '10000000' %} selected {% endif %} value="10000000">&#8358; 10 million</option>
						<option {% if request.GET.max_price == '50000000' %} selected {% endif %} value="50000000">&#8358; 50 million</option>
						<option {% if request.GET.max_price == '100000000' %} selected {% endif %} value="100000000">&#8358; 100 million</option>
						<option {% if request.GET.max_price == '500000000' %} selected {% endif %} value="500000000">&#8358; 500 million</option>
						<option {% if request.GET.max_price == '1000000000' %} selected {% endif %} value="1000000000">&#8358; 1 billion</option>
						<option {% if request.GET.max_price == '50000000000' %} selected {% endif %} value="1000000000">&#8358; 50 billion</option>
						<option {% if request.GET.max_price == '100000000000' %} selected {% endif %} value="1000000000">&#8358; 100 billion</option>
					</select>
				</div>
			</div>
			<button class="sidebar_search_button search_form_button">search</button>
		</form>
	</div>
</div>